# Generated by Django 5.2.4 on 2025-07-20 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_language_testcase_is_sample_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_sample',
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=3),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='core_submis_user_id_f6fcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-submitted'], name='core_submis_user_id_9ba837_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-submitted'], name='core_submis_problem_4978ff_idx'),
        ),
    ]
