# Generated by Django 5.2.4 on 2025-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testcase_options_testcase_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='core_submis_user_id_f6fcc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='core_submis_user_id_9ba837_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='core_submis_problem_4978ff_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('py', 'Python 3'), ('cpp', 'C++'), ('c', 'C')], default='py', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=10),
        ),
    ]
